language: java

dist: xenial
before_install:
  - sudo apt-get install -y gpgv2

jdk:
  - openjdk8

stages:
  - name: build
    if: branch = master
  - name: release
    if: branch = release

jobs:
  include:
    - stage: build
      script: 
        - mvn -B verify
    - stage: release
      script:
        - gpg --version
        - gpg2 --version
        - mvn -B -P release deploy
