language: java

cache:
  directories:
  - $HOME/.m2

dist: xenial

before_install:
  - sudo apt-get install -y gpgv2

jdk:
  - openjdk8

stages:
  - name: build
    if: branch = master
  - name: release
    if: branch = release

jobs:
  include:
    - stage: build
      script: 
        - mvn -B verify
    - stage: release
      script:
        - openssl version
        - gpg --version
        - gpg2 --version
        - openssl aes-256-cbc -pass env:OPENSSL_PASSWORD -in mobiliar-private-key.gpg.enc -out mobiliar-private-key.gpg -d -md sha256
        - gpg2 --batch --import mobiliar-private-key.gpg
        - export NEW_VERSION=2.1.$TRAVIS_BUILD_NUMBER
        - mvn -B -DnewVersion=$NEW_VERSION versions:set
        - mvn -B -P release -s settings-sonatype.xml install
#        - git tag release/$NEW_VERSION
#        - git push origin release/$NEW_VERSION
