language: java

dist: xenial

stages:
  - name: build
    if: branch = master
  - name: release
    if: branch = release

jobs:
  include:
    - stage: build
      script: 
        - mvn -B verify
    - stage: release
      script:
        - mvn -B -P release deploy
