language: java

cache:
  directories:
  - $HOME/.m2

dist: xenial

before_install:
  - sudo apt-get install pinentry-tty -y gpgv2

jdk:
  - openjdk8

stages:
  - name: build
    if: branch = master
  - name: release
    if: branch = release

jobs:
  include:
    - stage: build
      script: 
        - mvn -B verify site
    - stage: release
      script:
        - openssl version
        - gpg --version
        - gpg2 --version
        - echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
        - cat ~/.gnupg/gpg-agent.conf
        - openssl aes-256-cbc -pass env:OPENSSL_PASSWORD -in mobiliar-private-key.gpg.enc -out mobiliar-private-key.gpg -d -md sha256
        - gpg2 --batch --import mobiliar-private-key.gpg
        - gpg2 --list-secret-keys --keyid-format LONG
        - export GPG_TTY=$(tty)
        - export NEW_VERSION=2.1.$TRAVIS_BUILD_NUMBER
        - mvn -B -DnewVersion=$NEW_VERSION versions:set
        - mvn -B -P release -s settings-sonatype.xml install
#        - git tag release/$NEW_VERSION
#        - git push origin release/$NEW_VERSION
        - git config --global user.email "$GIT_RELEASE_EMAIL"
        - git config --global user.name "$GIT_RELEASE_USERNAME"
        - export GIT_TAG=release/$NEW_VERSION
        - git tag $GIT_TAG -a -m "tagging release"
        - git push -q https://$GITHUB_TOKEN@github.com/github.com/liimaorg/liima-maven-plugin.git --tags
        - ls -R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./target/site
  on:
    branch: release
